
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 28 10:25:27 CEST 2010
//----------------------------------------------------

package org.sindice.siren.qparser.ntriple;

/** CUP generated interface containing symbol constants. */
public interface NTripleQParserSymbols {
  /* terminals */
  public static final int MINUS = 4;
  public static final int AND = 2;
  public static final int LITERAL = 9;
  public static final int WILDCARD = 7;
  public static final int LPATTERN = 10;
  public static final int URIPATTERN = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int LPAREN = 5;
  public static final int OR = 3;
}

